import React, { useState, useMemo } from "react";
import { CloseIcon, CheckIcon } from "./SvgIcons";
import type { AlgoMetrics } from "@/services/algorithm";

interface CostReportModalProps {
  metrics: AlgoMetrics;
  routeCount: number;
  weekLabel: string;
  onClose: () => void;
}

const CostReportModal: React.FC<CostReportModalProps> = ({
  metrics,
  routeCount,
  weekLabel,
  onClose,
}) => {
  const [fuelPrice, setFuelPrice] = useState(1.8);
  const [driverRate, setDriverRate] = useState(28);
  const [co2Cost, setCo2Cost] = useState(0.05);
  const [copied, setCopied] = useState(false);

  const savings = useMemo(() => {
    const fuelCost = metrics.fuelSavedL * fuelPrice;
    const laborCost = metrics.hoursSaved * driverRate;
    const co2Value = metrics.co2AvoidedKg * co2Cost;
    const weekly = fuelCost + laborCost + co2Value;
    return {
      fuelCost,
      laborCost,
      co2Value,
      weekly,
      monthly: weekly * 4.33,
      annual: weekly * 52,
    };
  }, [metrics, fuelPrice, driverRate, co2Cost]);

  const reportText = useMemo(() => {
    return [
      `SmartRoute Weekly Savings Report — ${weekLabel}`,
      ``,
      `Routes optimized: ${routeCount}`,
      `Hours saved: ${metrics.hoursSaved.toFixed(1)} hrs`,
      `Fuel saved: ${metrics.fuelSavedL.toFixed(1)} L ($${savings.fuelCost.toFixed(2)})`,
      `CO₂ avoided: ${metrics.co2AvoidedKg.toFixed(1)} kg`,
      `Stops skipped: ${metrics.stopsSkipped}`,
      `Distance saved: ${metrics.kmSaved.toFixed(1)} km`,
      ``,
      `Cost Savings This Week: $${savings.weekly.toFixed(2)} CAD`,
      `Projected Monthly: $${savings.monthly.toFixed(0)} CAD`,
      `Projected Annual: $${savings.annual.toFixed(0)} CAD`,
      ``,
      `Assumptions: Fuel $${fuelPrice.toFixed(2)}/L · Driver $${driverRate}/hr · CO₂ $${co2Cost.toFixed(2)}/kg`,
      ``,
      `Generated by SmartRoute for Geotab`,
    ].join("\n");
  }, [metrics, savings, weekLabel, routeCount, fuelPrice, driverRate, co2Cost]);

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const InputField: React.FC<{
    label: string;
    value: number;
    onChange: (v: number) => void;
    prefix: string;
    suffix: string;
    step?: number;
  }> = ({ label, value, onChange, prefix, suffix, step = 0.1 }) => (
    <div>
      <label className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">
        {label}
      </label>
      <div className="flex items-center gap-1 mt-1">
        <span className="text-xs text-muted-foreground">{prefix}</span>
        <input
          type="number"
          value={value}
          onChange={(e) => onChange(Number(e.target.value))}
          step={step}
          min={0}
          className="w-20 px-2 py-1 text-xs rounded-lg bg-muted border border-border outline-none focus:ring-2 focus:ring-primary/30"
        />
        <span className="text-xs text-muted-foreground">{suffix}</span>
      </div>
    </div>
  );

  return (
    <div className="fixed inset-0 z-[3000] flex items-center justify-center bg-black/50 backdrop-blur-sm">
      <div className="bg-card rounded-2xl shadow-2xl w-full max-w-lg mx-4 overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border">
          <div>
            <h2 className="text-base font-extrabold text-foreground">Cost Savings Report</h2>
            <p className="text-xs text-muted-foreground mt-0.5">{weekLabel}</p>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-muted rounded-full transition">
            <CloseIcon size={16} color="hsl(210, 15%, 50%)" />
          </button>
        </div>

        <div className="p-6 space-y-5">
          {/* Metrics summary */}
          <div className="grid grid-cols-3 gap-3">
            {[
              { label: "Hours saved", value: `${metrics.hoursSaved.toFixed(1)} hrs` },
              { label: "Fuel saved", value: `${metrics.fuelSavedL.toFixed(1)} L` },
              { label: "CO₂ avoided", value: `${metrics.co2AvoidedKg.toFixed(1)} kg` },
              { label: "Stops skipped", value: String(metrics.stopsSkipped) },
              { label: "Distance saved", value: `${metrics.kmSaved.toFixed(1)} km` },
              { label: "Routes optimized", value: String(routeCount) },
            ].map((m) => (
              <div key={m.label} className="bg-muted/40 rounded-lg p-3 text-center">
                <div className="text-lg font-extrabold text-foreground">{m.value}</div>
                <div className="text-[10px] text-muted-foreground font-medium mt-0.5">{m.label}</div>
              </div>
            ))}
          </div>

          {/* Cost assumptions */}
          <div>
            <h3 className="text-xs font-bold text-foreground mb-3 uppercase tracking-widest">
              Cost Assumptions (editable)
            </h3>
            <div className="flex gap-4">
              <InputField label="Fuel price" value={fuelPrice} onChange={setFuelPrice} prefix="$" suffix="/L" />
              <InputField label="Driver rate" value={driverRate} onChange={setDriverRate} prefix="$" suffix="/hr" step={1} />
              <InputField label="CO₂ cost" value={co2Cost} onChange={setCo2Cost} prefix="$" suffix="/kg" step={0.01} />
            </div>
          </div>

          {/* Savings breakdown */}
          <div className="bg-primary/5 border border-primary/15 rounded-xl p-4 space-y-2">
            <div className="flex justify-between text-xs">
              <span className="text-muted-foreground">Fuel cost saved</span>
              <span className="font-bold text-foreground">${savings.fuelCost.toFixed(2)}</span>
            </div>
            <div className="flex justify-between text-xs">
              <span className="text-muted-foreground">Labor cost saved</span>
              <span className="font-bold text-foreground">${savings.laborCost.toFixed(2)}</span>
            </div>
            <div className="flex justify-between text-xs">
              <span className="text-muted-foreground">CO₂ credit value</span>
              <span className="font-bold text-foreground">${savings.co2Value.toFixed(2)}</span>
            </div>
            <div className="border-t border-primary/15 pt-2 mt-2 flex justify-between">
              <span className="text-sm font-bold text-foreground">This Week</span>
              <span className="text-lg font-extrabold text-primary">${savings.weekly.toFixed(2)}</span>
            </div>
          </div>

          {/* Projections */}
          <div className="flex gap-4">
            <div className="flex-1 bg-muted/40 rounded-lg p-3 text-center">
              <div className="text-lg font-extrabold text-foreground">${savings.monthly.toFixed(0)}</div>
              <div className="text-[10px] text-muted-foreground font-medium">Monthly projection</div>
            </div>
            <div className="flex-1 bg-muted/40 rounded-lg p-3 text-center">
              <div className="text-lg font-extrabold text-primary">${savings.annual.toFixed(0)}</div>
              <div className="text-[10px] text-muted-foreground font-medium">Annual projection</div>
            </div>
          </div>

          <p className="text-[10px] text-muted-foreground leading-relaxed">
            Projections assume consistent weekly optimization. Actual savings may vary based on route
            volume, seasonal demand, and fleet size.
          </p>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-border bg-muted/20">
          <span className="text-[10px] text-muted-foreground">
            Copy this report to paste into email or Slack
          </span>
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground text-xs font-bold rounded-lg hover:bg-primary/90 transition"
          >
            {copied ? (
              <>
                <CheckIcon size={14} color="white" />
                Copied!
              </>
            ) : (
              "Copy Report"
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

export default CostReportModal;
